export const DirectoryType = {
  0: '未收录音乐',
  1: '单曲',
  2: '专辑',
  3: 'Mini专辑',
  4: '原声集',
  5: 'Planet',  
  6: '广播',  
  // 0: 'Other',
  // 1: 'Single',
  // 2: 'Album',
  // 3: 'Mini Album',
  // 4: 'Original Album',
  // 5: 'Planet',
  // 6: 'FM',  
}
